In [57]:
import pandas as pd
import altair as alt
from vega_datasets import data
import json, urllib.request
import numpy as np

In [10]:
json_url = data.earthquakes.url
with urllib.request.urlopen(json_url) as f:
    raw = json.load(f)

In [18]:
raw['features']

[{'type': 'Feature',
  'properties': {'mag': 2,
   'place': '4km W of Castaic, CA',
   'time': 1517966773840,
   'updated': 1517966996303,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci37868143',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci37868143.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 62,
   'net': 'ci',
   'code': '37868143',
   'ids': ',ci37868143,',
   'sources': ',ci,',
   'types': ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 7,
   'dmin': 0.04214,
   'rms': 0.35,
   'gap': 174,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 2.0 - 4km W of Castaic, CA'},
  'geometry': {'type': 'Point', 'coordinates': [-118.6671667, 34.4945, 26.49]},
  'id': 'ci37868143'},
 {'type': 'Feature',
  'properties': {'mag': 1.6,
   'place': '2km E of San Marino, CA',
   'time': 1517966037750,
   'updated': 1517966268248,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci37868135',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci37868135.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 39,
   'net': 'ci',
   'code': '37868135',
   'ids': ',ci37868135,',
   'sources': ',ci,',
   'types': ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 5,
   'dmin': 0.2619,
   'rms': 0.12,
   'gap': 141,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.6 - 2km E of San Marino, CA'},
  'geometry': {'type': 'Point', 'coordinates': [-118.0873333, 34.12, 9.72]},
  'id': 'ci37868135'},
 {'type': 'Feature',
  'properties': {'mag': 0.54,
   'place': '11km NE of Aguanga, CA',
   'time': 1517965273890,
   'updated': 1517965499017,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci37868127',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci37868127.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 4,
   'net': 'ci',
   'code': '37868127',
   'ids': ',ci37868127,',
   'sources': ',ci,',
   'types': ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 24,
   'dmin': 0.06711,
   'rms': 0.16,
   'gap': 64,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 0.5 - 11km NE of Aguanga, CA'},
  'geometry': {'type': 'Point', 'coordinates': [-116.7943333, 33.518, 5.04]},
  'id': 'ci37868127'},
 {'type': 'Feature',
  'properties': {'mag': 3.8,
   'place': '300km SE of Kodiak, Alaska',
   'time': 1517964979027,
   'updated': 1517966781617,
   'tz': -600,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18384056',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18384056.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 222,
   'net': 'ak',
   'code': '18384056',
   'ids': ',ak18384056,',
   'sources': ',ak,',
   'types': ',geoserve,origin,phase-data,',
   'nst': None,
   'dmin': None,
   'rms': 0.84,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 3.8 - 300km SE of Kodiak, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-149.145, 55.7729, 7.7]},
  'id': 'ak18384056'},
 {'type': 'Feature',
  'properties': {'mag': 0.66,
   'place': '10km WNW of The Geysers, CA',
   'time': 1517964860110,
   'updated': 1517965504730,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nc72965406',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nc72965406.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 7,
   'net': 'nc',
   'code': '72965406',
   'ids': ',nc72965406,',
   'sources': ',nc,',
   'types': ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 15,
   'dmin': 0.01646,
   'rms': 0.04,
   'gap': 80,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 0.7 - 10km WNW of The Geysers, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-122.8560028, 38.8246651, 1.47]},
  'id': 'nc72965406'},
 {'type': 'Feature',
  'properties': {'mag': 1.7,
   'place': '32km W of Healy, Alaska',
   'time': 1517963917057,
   'updated': 1517964249989,
   'tz': -540,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18384036',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18384036.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 44,
   'net': 'ak',
   'code': '18384036',
   'ids': ',ak18384036,',
   'sources': ',ak,',
   'types': ',geoserve,origin,',
   'nst': None,
   'dmin': None,
   'rms': 0.44,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.7 - 32km W of Healy, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-149.6259, 63.8969, 140.3]},
  'id': 'ak18384036'},
 {'type': 'Feature',
  'properties': {'mag': 3.1,
   'place': '267km ESE of Kodiak, Alaska',
   'time': 1517963220510,
   'updated': 1517965488928,
   'tz': -600,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18384019',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18384019.geojson',
   'felt': 0,
   'cdi': 1,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 148,
   'net': 'ak',
   'code': '18384019',
   'ids': ',ak18384019,',
   'sources': ',ak,',
   'types': ',dyfi,geoserve,origin,phase-data,',
   'nst': None,
   'dmin': None,
   'rms': 0.94,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 3.1 - 267km ESE of Kodiak, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-148.6001, 56.5687, 10]},
  'id': 'ak18384019'},
 {'type': 'Feature',
  'properties': {'mag': 1.23,
   'place': '2km S of Mentone, CA',
   'time': 1517963053550,
   'updated': 1517963265163,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci37868079',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci37868079.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 23,
   'net': 'ci',
   'code': '37868079',
   'ids': ',ci37868079,',
   'sources': ',ci,',
   'types': ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 46,
   'dmin': 0.0236,
   'rms': 0.2,
   'gap': 67,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.2 - 2km S of Mentone, CA'},
  'geometry': {'type': 'Point', 'coordinates': [-117.137, 34.0473333, 6.57]},
  'id': 'ci37868079'},
 {'type': 'Feature',
  'properties': {'mag': 2.8,
   'place': '282km SE of Kodiak, Alaska',
   'time': 1517962942325,
   'updated': 1517967641825,
   'tz': -600,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18384018',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18384018.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 121,
   'net': 'ak',
   'code': '18384018',
   'ids': ',ak18384018,',
   'sources': ',ak,',
   'types': ',geoserve,origin,phase-data,',
   'nst': None,
   'dmin': None,
   'rms': 0.38,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 2.8 - 282km SE of Kodiak, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-148.6645, 56.2823, 9.1]},
  'id': 'ak18384018'},
 {'type': 'Feature',
  'properties': {'mag': 3.8,
   'place': '11km WSW of Willow, Alaska',
   'time': 1517962722963,
   'updated': 1517965768875,
   'tz': -540,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18384001',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18384001.geojson',
   'felt': 46,
   'cdi': 3.4,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 238,
   'net': 'ak',
   'code': '18384001',
   'ids': ',ak18384001,',
   'sources': ',ak,',
   'types': ',dyfi,geoserve,origin,',
   'nst': None,
   'dmin': None,
   'rms': 1.07,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 3.8 - 11km WSW of Willow, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-150.2399, 61.7028, 100]},
  'id': 'ak18384001'},
 {'type': 'Feature',
  'properties': {'mag': 3.5,
   'place': '7km NNW of Houston, Alaska',
   'time': 1517962720756,
   'updated': 1517966398650,
   'tz': -540,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18383983',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18383983.geojson',
   'felt': 0,
   'cdi': 1,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 188,
   'net': 'ak',
   'code': '18383983',
   'ids': ',ak18383983,us1000chw0,',
   'sources': ',ak,us,',
   'types': ',dyfi,geoserve,origin,phase-data,',
   'nst': None,
   'dmin': None,
   'rms': 0.77,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 3.5 - 7km NNW of Houston, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-149.8542, 61.6978, 22.7]},
  'id': 'ak18383983'},
 {'type': 'Feature',
  'properties': {'mag': 1.4,
   'place': '20km NNE of Badger, Alaska',
   'time': 1517962260058,
   'updated': 1517963363803,
   'tz': -540,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18383974',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18383974.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 30,
   'net': 'ak',
   'code': '18383974',
   'ids': ',ak18383974,',
   'sources': ',ak,',
   'types': ',geoserve,origin,',
   'nst': None,
   'dmin': None,
   'rms': 0.66,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.4 - 20km NNE of Badger, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-147.408, 64.9794, 0]},
  'id': 'ak18383974'},
 {'type': 'Feature',
  'properties': {'mag': 2.6,
   'place': '91km S of King Salmon, Alaska',
   'time': 1517962256802,
   'updated': 1517963136869,
   'tz': -540,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18383975',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18383975.geojson',
   'felt': 0,
   'cdi': 1,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 104,
   'net': 'ak',
   'code': '18383975',
   'ids': ',ak18383975,',
   'sources': ',ak,',
   'types': ',dyfi,geoserve,origin,',
   'nst': None,
   'dmin': None,
   'rms': 0.77,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 2.6 - 91km S of King Salmon, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-156.4712, 57.8731, 141.1]},
  'id': 'ak18383975'},
 {'type': 'Feature',
  'properties': {'mag': 0.96,
   'place': '10km WNW of The Geysers, CA',
   'time': 1517962245450,
   'updated': 1517962340976,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nc72965396',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nc72965396.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 14,
   'net': 'nc',
   'code': '72965396',
   'ids': ',nc72965396,',
   'sources': ',nc,',
   'types': ',geoserve,nearby-cities,origin,phase-data,',
   'nst': 14,
   'dmin': 0.003306,
   'rms': 0.03,
   'gap': 75,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 1.0 - 10km WNW of The Geysers, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-122.8541641, 38.8250008, 1.79]},
  'id': 'nc72965396'},
 {'type': 'Feature',
  'properties': {'mag': 4.7,
   'place': '7km E of Hualian, Taiwan',
   'time': 1517960631840,
   'updated': 1517962022040,
   'tz': 480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us1000chvf',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us1000chvf.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 340,
   'net': 'us',
   'code': '1000chvf',
   'ids': ',us1000chvf,',
   'sources': ',us,',
   'types': ',geoserve,origin,phase-data,',
   'nst': None,
   'dmin': 0.199,
   'rms': 0.9,
   'gap': 80,
   'magType': 'mb',
   'type': 'earthquake',
   'title': 'M 4.7 - 7km E of Hualian, Taiwan'},
  'geometry': {'type': 'Point', 'coordinates': [121.6773, 23.9887, 10]},
  'id': 'us1000chvf'},
 {'type': 'Feature',
  'properties': {'mag': 0.48,
   'place': '10km NE of Aguanga, CA',
   'time': 1517959375710,
   'updated': 1517962507985,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci37868055',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci37868055.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 4,
   'net': 'ci',
   'code': '37868055',
   'ids': ',ci37868055,',
   'sources': ',ci,',
   'types': ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 27,
   'dmin': 0.07667,
   'rms': 0.11,
   'gap': 45,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 0.5 - 10km NE of Aguanga, CA'},
  'geometry': {'type': 'Point', 'coordinates': [-116.7895, 33.5021667, 5.27]},
  'id': 'ci37868055'},
 {'type': 'Feature',
  'properties': {'mag': 4.7,
   'place': '13km ENE of Hualian, Taiwan',
   'time': 1517958703100,
   'updated': 1517960141040,
   'tz': 480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/us1000chuk',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/us1000chuk.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 340,
   'net': 'us',
   'code': '1000chuk',
   'ids': ',us1000chuk,',
   'sources': ',us,',
   'types': ',geoserve,origin,phase-data,',
   'nst': None,
   'dmin': 0.175,
   'rms': 0.84,
   'gap': 79,
   'magType': 'mb',
   'type': 'earthquake',
   'title': 'M 4.7 - 13km ENE of Hualian, Taiwan'},
  'geometry': {'type': 'Point', 'coordinates': [121.7221, 24.0424, 10]},
  'id': 'us1000chuk'},
 {'type': 'Feature',
  'properties': {'mag': 1.9,
   'place': '37km NW of Willow, Alaska',
   'time': 1517956909776,
   'updated': 1517963892027,
   'tz': -540,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18381092',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18381092.geojson',
   'felt': 0,
   'cdi': 1,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 56,
   'net': 'ak',
   'code': '18381092',
   'ids': ',ak18381092,',
   'sources': ',ak,',
   'types': ',dyfi,geoserve,origin,',
   'nst': None,
   'dmin': None,
   'rms': 0.54,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.9 - 37km NW of Willow, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-150.4985, 62.0043, 25]},
  'id': 'ak18381092'},
 {'type': 'Feature',
  'properties': {'mag': 1,
   'place': '111km NW of Talkeetna, Alaska',
   'time': 1517956889592,
   'updated': 1517961687447,
   'tz': -540,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ak18381093',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ak18381093.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 15,
   'net': 'ak',
   'code': '18381093',
   'ids': ',ak18381093,',
   'sources': ',ak,',
   'types': ',geoserve,origin,phase-data,',
   'nst': None,
   'dmin': None,
   'rms': 0.41,
   'gap': None,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 1.0 - 111km NW of Talkeetna, Alaska'},
  'geometry': {'type': 'Point', 'coordinates': [-151.5091, 63.0943, 3.2]},
  'id': 'ak18381093'},
 {'type': 'Feature',
  'properties': {'mag': 1.56,
   'place': '18km NW of Parkfield, CA',
   'time': 1517955951050,
   'updated': 1517963281550,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nc72965386',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nc72965386.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 37,
   'net': 'nc',
   'code': '72965386',
   'ids': ',nc72965386,',
   'sources': ',nc,',
   'types': ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 19,
   'dmin': 0.0314,
   'rms': 0.05,
   'gap': 106,
   'magType': 'md',
   'type': 'earthquake',
   'title': 'M 1.6 - 18km NW of Parkfield, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-120.5753326, 36.0098343, 1.21]},
  'id': 'nc72965386'},
 {'type': 'Feature',
  'properties': {'mag': 2.1,
   'place': '24km WNW of Battle Mountain, Nevada',
   'time': 1517955194906,
   'updated': 1517956073863,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nn00620911',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nn00620911.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 68,
   'net': 'nn',
   'code': '00620911',
   'ids': ',nn00620911,',
   'sources': ',nn,',
   'types': ',geoserve,origin,phase-data,',
   'nst': 7,
   'dmin': 0.292,
   'rms': 0.1726,
   'gap': 107.76,
   'magType': 'ml',
   'type': 'explosion',
   'title': 'M 2.1 Explosion - 24km WNW of Battle Mountain, Nevada'},
  'geometry': {'type': 'Point', 'coordinates': [-117.2048, 40.7226, 1]},
  'id': 'nn00620911'},
 {'type': 'Feature',
  'properties': {'mag': 0.33,
   'place': '11km N of Anza, CA',
   'time': 1517954843800,
   'updated': 1517955064884,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci37868015',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci37868015.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'automatic',
   'tsunami': 0,
   'sig': 2,
   'net': 'ci',
   'code': '37868015',
   'ids': ',ci37868015,',
   'sources': ',ci,',
   'types': ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 10,
   'dmin': 0.101,
   'rms': 0.31,
   'gap': 192,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 0.3 - 11km N of Anza, CA'},
  'geometry': {'type': 'Point',
   'coordinates': [-116.6631667, 33.6496667, 7.36]},
  'id': 'ci37868015'},
 {'type': 'Feature',
  'properties': {'mag': 0.82,
   'place': '9km ENE of Aguanga, CA',
   'time': 1517954786040,
   'updated': 1517961473355,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/ci37868007',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/ci37868007.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',
   'tsunami': 0,
   'sig': 10,
   'net': 'ci',
   'code': '37868007',
   'ids': ',ci37868007,',
   'sources': ',ci,',
   'types': ',geoserve,nearby-cities,origin,phase-data,scitech-link,',
   'nst': 31,
   'dmin': 0.08937,
   'rms': 0.18,
   'gap': 39,
   'magType': 'ml',
   'type': 'earthquake',
   'title': 'M 0.8 - 9km ENE of Aguanga, CA'},
  'geometry': {'type': 'Point', 'coordinates': [-116.7865, 33.4858333, 4.78]},
  'id': 'ci37868007'},
 {'type': 'Feature',
  'properties': {'mag': 2,
   'place': '34km NW of Carlin, Nevada',
   'time': 1517954525430,
   'updated': 1517956270289,
   'tz': -480,
   'url': 'https://earthquake.usgs.gov/earthquakes/eventpage/nn00620907',
   'detail': 'https://earthquake.usgs.gov/earthquakes/feed/v1.0/detail/nn00620907.geojson',
   'felt': None,
   'cdi': None,
   'mmi': None,
   'alert': None,
   'status': 'reviewed',

In [20]:
df = pd.json_normalize(raw['features'])
df

,type,id,properties.mag,properties.place,properties.time,properties.updated,properties.tz,properties.url,properties.detail,properties.felt,...,properties.types,properties.nst,properties.dmin,properties.rms,properties.gap,properties.magType,properties.type,properties.title,geometry.type,geometry.coordinates
0,Feature,ci37868143,2.00,"4km W of Castaic, CA",1517966773840,1517966996303,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",geoserve,nearby-cities,origin,phase-data,scit...",7.0,0.04214,0.35,174.0,ml,earthquake,"M 2.0 - 4km W of Castaic, CA",Point,"[-118.6671667, 34.4945, 26.49]"
1,Feature,ci37868135,1.60,"2km E of San Marino, CA",1517966037750,1517966268248,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",geoserve,nearby-cities,origin,phase-data,scit...",5.0,0.26190,0.12,141.0,ml,earthquake,"M 1.6 - 2km E of San Marino, CA",Point,"[-118.0873333, 34.12, 9.72]"
2,Feature,ci37868127,0.54,"11km NE of Aguanga, CA",1517965273890,1517965499017,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",geoserve,nearby-cities,origin,phase-data,scit...",24.0,0.06711,0.16,64.0,ml,earthquake,"M 0.5 - 11km NE of Aguanga, CA",Point,"[-116.7943333, 33.518, 5.04]"
3,Feature,ak18384056,3.80,"300km SE of Kodiak, Alaska",1517964979027,1517966781617,-600,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",geoserve,origin,phase-data,",NaN,NaN,0.84,NaN,ml,earthquake,"M 3.8 - 300km SE of Kodiak, Alaska",Point,"[-149.145, 55.7729, 7.7]"
4,Feature,nc72965406,0.66,"10km WNW of The Geysers, CA",1517964860110,1517965504730,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",geoserve,nearby-cities,origin,phase-data,scit...",15.0,0.01646,0.04,80.0,md,earthquake,"M 0.7 - 10km WNW of The Geysers, CA",Point,"[-122.8560028, 38.8246651, 1.47]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1702,Feature,us2000crl8,4.70,"232km ENE of Raoul Island, New Zealand",1517365017350,1517368678040,-720,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",geoserve,origin,phase-data,",NaN,2.10500,1.18,142.0,mb,earthquake,"M 4.7 - 232km ENE of Raoul Island, New Zealand",Point,"[-175.7709, -28.3222, 10]"
1703,Feature,us1000cdjq,2.00,"33km W of Raton, New Mexico",1517364466860,1517530950040,-420,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",geoserve,origin,phase-data,",NaN,0.06900,0.14,89.0,ml,earthquake,"M 2.0 - 33km W of Raton, New Mexico",Point,"[-104.8072, 36.8543, 4.1]"
1704,Feature,us2000crkq,5.30,"50km NNW of Sangiang, Indonesia",1517364031800,1517423633040,480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,4.0,...,",dyfi,geoserve,moment-tensor,origin,phase-data,",NaN,2.98600,1.07,53.0,mb,earthquake,"M 5.3 - 50km NNW of Sangiang, Indonesia",Point,"[118.7906, -7.8628, 15.18]"
1705,Feature,mb80279649,1.35,"20km NNE of Lima, Montana",1517364015660,1517411000340,-420,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",geoserve,origin,phase-data,",13.0,0.23500,0.11,115.0,ml,earthquake,"M 1.4 - 20km NNE of Lima, Montana",Point,"[-112.5183333, 44.8181667, -2.15]"
1706,Feature,uw61345682,0.31,"37km NNE of Amboy, Washington",1517363399650,1517942380200,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,",geoserve,origin,phase-data,",7.0,0.01200,0.11,108.0,ml,earthquake,"M 0.3 - 37km NNE of Amboy, Washington",Point,"[-122.197, 46.2035, 3.28]"

In [54]:
df.columns

Index(['type', 'id', 'properties.mag', 'properties.place', 'properties.time',
       'properties.updated', 'properties.tz', 'properties.url',
       'properties.detail', 'properties.felt', 'properties.cdi',
       'properties.mmi', 'properties.alert', 'properties.status',
       'properties.tsunami', 'properties.sig', 'properties.net',
       'properties.code', 'properties.ids', 'properties.sources',
       'properties.types', 'properties.nst', 'properties.dmin',
       'properties.rms', 'properties.gap', 'properties.magType',
       'properties.type', 'properties.title', 'geometry.type',
       'geometry.coordinates', 'Lat', 'Long', 'date_str'],
      dtype='object')

In [26]:
long_ = []
lat_ = []
for i in df['geometry.coordinates']:
    long_.append(i[0])
    lat_.append(i[1])
df['Lat'] = lat_
df["Long"] = long_

In [28]:
df["date_str"] = pd.to_datetime(df["properties.time"])

In [92]:
df["date_str"]

0      1970-01-01 00:25:17.966773840
1      1970-01-01 00:25:17.966037750
2      1970-01-01 00:25:17.965273890
3      1970-01-01 00:25:17.964979027
4      1970-01-01 00:25:17.964860110
                    ...
1702   1970-01-01 00:25:17.365017350
1703   1970-01-01 00:25:17.364466860
1704   1970-01-01 00:25:17.364031800
1705   1970-01-01 00:25:17.364015660
1706   1970-01-01 00:25:17.363399650
Name: date_str, Length: 1707, dtype: datetime64[ns]

In [89]:
df['magnitude'] = df['properties.mag'].astype(float)

In [21]:
counties = alt.topo_feature(data.us_10m.url, 'counties')
source = data.unemployment.url

map = alt.Chart(counties).mark_geoshape().encode(
    color=alt.Color('rate:Q',
                    title='UE Rate'
                    ),
    tooltip=['rate:Q','id:O']
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(source, 'id', ['rate'])
).project(
    type='albersUsa'
).properties(
    width=750,
    height=400
)

In [34]:
countries = alt.topo_feature(data.world_110m.url, 'countries')

In [46]:
alt.Chart(df).mark_circle(size=30).encode(
    longitude='Long:Q',
    latitude='Lat:Q',
    tooltip=['properties.mag']
).project(
    type='mercator'
).properties(
    width=700,
    height=400,
    title='Earthquakes (lat/lon)'
)

alt.Chart(...)

In [48]:
alt.layer(
    alt.Chart(countries).mark_geoshape(fill='lightgray', stroke='white'),
    alt.Chart(df).mark_circle(size=10, color='red').encode(
        longitude='Long:Q',
        latitude='Lat:Q'
    )
).project('naturalEarth1').properties(width=700, height=400)

alt.LayerChart(...)

In [90]:
countries = alt.topo_feature(data.world_110m.url, "countries")

base = (
    alt.Chart(countries)
    .mark_geoshape(fill="lightgray", stroke="white")
    .project(type="naturalEarth1")
    .properties(width=900, height=480)
)

# Reveal only up to the current step

points = (
    alt.Chart(df)
    .mark_circle(size=1000)
    .encode(
        longitude="Long:Q",
        latitude="Lat:Q",
        color=alt.Color(
            "magnitude:Q",
            scale=alt.Scale(scheme="inferno"),
            legend=alt.Legend(title="Magnitude")),
        tooltip=["magnitude:Q", "step:Q", "properties.type:N", "date_str:T"],
    )
)

In [91]:
chart = (base + points).properties(title="Adding Points Over Time (Play/Pause/Reset)")
chart

alt.LayerChart(...)

In [52]:
# map_placeholder = st.empty()

for i, row in df.iterrows():
    new_row = pd.DataFrame({"lat": [lat], "lon": [lon]})
    # points = pd.concat([points, new_row], ignore_index=True)
    
    # chart = alt.Chart(points).mark_circle(size=150, color='red').encode(
    #     longitude='lon:Q',
    #     latitude='lat:Q'
    # ).project('mercator').properties(width=600, height=400)
    
    # map_placeholder.altair_chart(chart)
    # time.sleep(1)
    # print(row['Lat'])

34.4945
34.12
33.518
55.7729
38.8246651
63.8969
56.5687
34.0473333
56.2823
61.7028
61.6978
64.9794
57.8731
38.8250008
23.9887
33.5021667
24.0424
62.0043
63.0943
36.0098343
40.7226
33.6496667
33.4858333
40.9433
38.1608
38.8209991
36.6781
38.3974
9.4429
61.0186
62.34
55.8526
24.054
62.2947
60.2249
60.0371
59.8703
36.9138336
58.1913
33.4961667
33.7835
-32.4714
33.2346667
58.9587
23.9506
37.7994
40.2825
38.8380013
23.942
35.6961667
38.8371658
-18.9718
37.2339
18.171
24.0413
24.0521
39.9385
17.911
39.8157
33.1596667
38.8214989
19.3948333
33.3198333
19.3831667
37.9975014
38.8223343
65.4043
19.1508333
56.1815
23.9342
38.3726
33.577
24.1737
33.5786667
33.4973333
45.3583333
33.6703333
56.2507
57.9207
40.0627
37.6343346
40.048
19.0268
33.2496667
36.5584984
36.9329987
60.5649
36.7501
61.4805
33.7426667
60.5003
33.7415
18.2985
37.5316667
61.5779
36.5750008
38.8371658
38.0526
33.4958333
37.6145
33.5081667
38.8273315
40.524334
37.1792
38.822834
33.6545
33.4523333
35.9628
37.6616667
63.8834
38.8370018
38.8181648
33.3025
34.1715
38.0647
63.093
39.168
37.4003334
34.2211667
-14.2192
36.4442
55.9877
33.5183333
37.6083333
37.4561667
56.3975
56.4413
24.0383
38.035
39.3855
60.0481
38.8436661
33.4895
46.6056667
17.9156
37.6443333
39.739
38.8175011
35.712
61.456
35.4264
33.3568333
36.5665016
37.6053333
36.471
0.6058
50.1326
37.5546667
19.522
34.0201667
37.6696667
38.3928
18.1293
18.1566
51.8182
45.7451667
36.2369995
38.8064995
34.9573333
17.8606
38.8264999
37.5478333
64.664
60.861
24.1594
63.1469
63.1156
18.1555
40.0288315
-35.2607
19.3185
35.7773333
62.4169
33.5103333
46.2438333
41.535
33.9685
38.0549
-34.7746
61.5429
39.3906
36.5073318
19.0596
33.0061667
33.5956667
19.4201667
33.8991667
35.7146667
38.0547
39.1457
33.4856667
33.4673333
46.1946667
37.5211667
61.4336
58.9754
37.3971
37.4024
35.6576667
40.2048
60.9065
63.5389
35.7861667
37.2623
46.1865
42.5478333
18.2431
37.4249
38.4441667
38.8030014
33.5108333
34.1523333
34.1448333
61.9128
61.1541
33.9643333
34.1156667
38.0540009
37.4209
40.043335
40.0416679
34.1511667
58.3475
37.4208
35.8561667
35.0351667
62.2009
30.6943
38.4082
61.6655
60.1187
38.7851677
37.6548333
46.2116667
64.5697
44.649
61.7378
38.6941
-58.9233
38.5488
38.8133316
33.4905
37.6561667
-15.9412
46.4778333
-16.1718
38.3651
33.8616676
60.1136
38.587
36.0094986
36.8903351
36.0008316
34.0235
56.4981
62.221
36.0235
34.7005
37.6386667
26.9956
33.4963333
64.8266
38.8074989
59.782
36.4253
63.2224
61.2992
33.596
38.6601
45.9963333
56.2035
33.183
33.1865
38.8318329
19.362
61.7341
63.8823
38.8118324
13.0373
-12.8818
56.3778
38.0636
38.0716667
37.5144997
60.7142
63.1151
33.2598333
62.3982
60.2396
33.9896667
35.991333
45.822
36.036335
38.8356667
38.8346672
18.1568
35.9965
56.1791
38.8185005
55.8559
38.0627
18.2524
60.1555
-8.446
33.1635
37.3144
38.8156662
-19.3174
36.5311667
24.1032
63.3028
33.2585
44.6745
63.0904
50.3176
60.2306
64.5586
-20.7575
33.4236667
33.4996667
38.8199997
33.2231667
33.1811667
41.0771
32.7438333
33.4935
38.0649
36.4121
32.7588333
38.8178329
63.0251
61.1227
41.071
50.0039
37.7416667
57.555
62.8396
33.5096667
63.3496
39.6013
42.0086667
59.1711
36.7043343
44.5615
34.1613333
37.5771667
59.6704
38.0571
38.3874
36.03
61.7341
38.051
41.2328333
33.4938333
42.0111667
56.2926
33.4333333
36.0061684
37.5711667
32.7913333
64.8773
19.0505
33.42
37.5631667
33.1831667
33.9691667
13.1817
38.0624
34.1215
36.481
36.4720001
36.472168
33.4153333
53.6741
33.1741667
33.1806667
-35.5315
40.4099
59.8673
33.1838333
17.8496
33.1843333
38.1379
62.5954
60.5653
66.2619
18.4725
36.0355
36.0279
62.5572
46.2615
19.4753333
38.8396683
38.816
37.5608333
36.127
63.1783
38.7043333
33.478
63.091
37.1583
36.9193
63.5591
33.8703333
33.5111667
38.8198318
36.041
37.1815
33.5116667
37.2248
33.7406667
14.4098
19.2398338
18.1165
37.1412
36.4729996
36.491
18.2058
33.7441667
19.2054996
63.0894
61.5276
39.3926
19.4055
60.5531
19.0895
40.0195
35.9117
37.546
38.3826
33.4925
56.6453
47.6721667
37.636
46.8178333
37.1449
33.4976667
33.4816667
40.0273333
38.804
37.1454
33.4906667
61.9907
38.822834
38.385
33.682
63.2033
38.8204994
56.4235
38.579
32.4066667
33.4965
37.1439
59.9616
37.3114
39.6909
42.0078333
33.7118333
47.7076667
17.9716
38.8504982
37.3143
63.4665
42.0033333
37.6613333
35.0425
46.9026667
37.1418
63.5738
37.1335
33.5145
62.8003
64.73
38.0717
37.1448
38.2825
37.53
61.8888
63.4361
42.0051667
33.4853333
38.8180008
47.5676667
42.0001667
38.8429985
35.8915
35.8911667
64.5751
33.4915
63.2922
45.1558333
37.6466667
59.8561
33.4971667
38.8424988
37.566
33.7388333
35.8878333
35.891
62.7579
33.0408333
45.826
37.5723343
37.5461667
45.2457
-17.4117
32.579
37.4568333
35.8921667
33.5133333
56.0937
38.838501
37.6358333
33.5068333
37.6386667
35.9697
46.6095
37.1476
37.533
37.147
37.5751667
38.8144989
19.4025
38.8153343
-9.1216
38.072
37.1697
33.5061667
38.555
38.0645
38.802166
33.4935
39.3825
33.4886667
36.7931
38.0662
33.8046667
38.0654
37.1457
33.1976667
62.5999
38.0024986
-39.0812
53.1607
61.4602
64.6852
38.429
37.533
34.0696667
33.513
34.0185
37.6363333
37.1538
37.4188333
34.0498333
38.3987
33.4905
37.1503
37.1417
24.1665
37.1446
19.5271
33.3465
38.0578
38.0516
38.0648
57.3404
38.831665
36.9944
37.3441
39.4586
38.0673
67.2085
37.1156
37.1312
37.1298
38.0613
62.7678
39.9036
61.5084
37.6098333
24.1836
62.794
39.7817
37.8765
38.8204994
6.7197
62.1221
-34.6404
33.4871667
62.7539
33.4753333
38.0588
57.6599
38.057
60.5537
38.0537
35.4811667
24.0972
24.1247
24.137
38.0612
33.5191667
24.1595
33.1908333
40.0275
38.0706
82.7981
37.5436667
38.0205
35.1813333
61.2265
38.063
40.0035
33.4886667
61.1794
82.9954
83.0422
45.5492
65.0225
24.1692
33.4901667
36.3596
18.2595
33.71
36.7639
34.0025
59.0719
37.644165
37.6498333
37.6353333
33.7905
37.6489983
64.7064
19.7600002
-26.9732
33.6793333
19.365
33.0318333
36.1383333
39.4105
38.6722
37.66
37.6593333
37.5385
38.7901649
38.8353348
33.687
42.0715
38.4294
39.3902
56.4338
33.515
63.3144
38.3789
60.094
34.6823
18.7096
36.6523
38.1268
19.2321663
61.6335
-29.5013
62.1091
45.0731667
33.6748333
59.7443
33.6733333
16.2174
33.496
37.4661
39.7455
33.6736667
61.7494
33.9343333
19.2018337
51.3199
53.1435
45.029
33.5348333
37.2265
34.2863333
38.4956
33.4853333
33.4861667
39.5888
33.476
39.5585
17.8643
19.7541667
62.2905
63.7367
37.5203333
60.7703
46.8888333
48.6276667
36.7764
33.1845
60.2571
59.7255
39.3004
38.3039
32.9275
35.9753333
36.0144997
38.3982
46.1985
33.4888333
33.3503333
32.6748333
37.512001
19.3666668
37.5168343
38.3741
59.7535
35.3763
19.3681667
36.0093333
34.0538333
38.8428345
44.5318333
56.3878
36.5066681
38.0376667
59.8879
33.4853333
33.4956667
17.897
37.1183319
33.4858333
38.8253326
33.4993333
46.1936667
36.586834
36.469
60.7328
62.0685
38.0681
56.3537
33.4998333
37.6418333
17.929
37.4056667
44.7406667
36.5873337
37.6351662
37.635334
33.5493333
33.4925
62.1653
61.036
37.5445
63.106
19.3385
-4.7121
33.488
37.637001
37.6458333
61.6656
51.6434
62.2351
33.9108333
37.6096667
37.6425
33.4903333
38.8131676
33.965
33.4886667
38.8465004
38.8336678
33.4938333
65.0006
56.17
33.483
61.9526
37.6356659
33.4798333
-34.8831
19.1815
56.2717
-1.3392
39.7837
48.6031667
48.5915
37.5498333
33.494
33.9651667
63.3912
1.099
19.4273333
61.2805
33.5051667
39.9232
35.7471667
34.0163333
38.3772
33.4026667
39.3774
38.3782
35.3211667
61.4318
61.4223
37.6373329
46.608
33.2606667
35.7453333
36.5846667
37.6336667
46.8398333
39.3934
36.8573
36.8069
63.5045
33.4873333
38.7301
63.3894
32.9248333
33.9336667
32.9235
37.5235
62.0561
34.2013333
32.6481667
33.3255
61.4379
24.1489
41.7638333
37.6339989
38.8248329
31.2425
18.1481
33.4981667
36.039
38.8166656
61.2955
38.833168
59.8338
38.8050003
35.9900017
38.8101654
7.168
36.3594
64.6294
38.8120003
19.1988335
39.9793
55.9413
38.3223
38.2764
38.2355
37.6368333
33.4878333
38.3723
56.2548
36.0927
38.3252
38.378
38.3227
38.3748
37.5228333
37.3062
59.3833
60.9821
46.9523333
38.3741
33.5135
56.2313
18.1188
35.2786667
38.0571
45.3133333
38.3679
33.4338333
37.5153351
59.2129
37.5159988
33.7266667
20.5794
38.8334999
38.8419991
35.5501671
43.5686667
62.7729
38.8349991
33.7215
33.6941667
59.2753
39.3862
33.4971667
36.3656654
35.2728333
35.7721672
-7.537
39.3902
47.564
33.0535
37.6329994
-56.2764
46.682
43.3583
37.6373329
61.6026
44.4208333
32.9295
37.6344986
63.5399
38.0223
33.4996667
61.5967
32.7875
59.5271
32.925
37.5126667
38.3957
62.369
37.6355
37.6358333
33.4905
63.6252
37.6365
33.1611667
37.6363333
61.182
39.3883
39.7482
39.9632
37.6349983
37.6368332
37.6365013
37.6363335
64.5138
19.2883
38.4676
37.7425003
36.0355
33.3018333
37.2158
38.2268
39.3859
33.177
33.0488333
63.7136
51.7976
51.8429
38.8041649
44.7283333
66.2613
33.6943333
33.597
34.1786667
55.971
33.4788333
61.457
33.163
38.8068352
33.499
33.509
36.9503
56.4877
39.4067
60.4852
33.6733333
63.2496
40.6966667
37.044
33.4968333
37.662
33.495
61.182
33.489
33.4831667
19.1671667
38.0597
18.95
37.6575
38.0428333
82.7623
39.3785
38.3902
34.1398333
36.5929985
38.8256683
36.0423333
33.4906667
39.4824
33.492
33.9268333
33.4956667
-6.3139
55.9404
17.961
35.9731667
-6.827
35.1003333
33.227
34.2176667
37.2797
33.4933333
59.8165
33.5281667
61.2401
40.801
39.1007
38.8089981
39.1028
46.1945
37.9868
38.8188324
37.4945
33.4955
62.8943
37.4936667
38.8624992
37.2073
46.0968333
32.8955
33.4851667
19.3453
55.884
46.3341667
19.3018333
38.601
19.3028336
17.911
57.9952
34.0285
46.1263333
47.3936667
13.734
35.9516667
46.4436667
38.8221664
33.4921667
32.8998333
46.8878333
18.253
33.5021667
38.7926674
37.5185
18.6545
34.0146667
36.8654
49.2461667
-41.6706
38.8429985
62.869
44.2678
38.8300018
33.8768333
33.9755
36.024
-7.5723
65.2486
60.8152
39.3028
39.2515
36.0055
33.4878333
39.3205
18.82
19.097
19.1745
32.642
18.749
33.2731667
20.2575
59.1223
46.9916667
-8.1536
38.5238
36.1268333
36.1398333
18.4531
38.2702
-22.3395
38.5049
38.8154984
46.0048333
38.8326683
59.8388
33.5233333
46.258
38.7891655
18.1591
38.8014984
33.5103333
33.4953333
36.5833321
38.8326683
37.741333
63.0252
36.8483
44.731
33.0478333
35.8006668
33.9953333
19.2036667
33.4988333
40.4512
38.8209991
34.2148333
60.7165
40.7528333
38.3941
38.6502
37.5246
17.939
64.7357
57.9476
73.0195
37.6811676
35.7921667
61.7168
33.4945
36.0816667
66.6532
33.2135
37.607
19.4811667
39.3953
63.0927
33.2243333
38.4018
33.4883333
32.6106667
33.8831667
19.4806667
61.5
33.4853333
63.4215
39.8463333
33.4836667
33.2486667
-65.8617
37.534
33.497
33.996
38.8321648
11.2106
33.4101667
38.8188324
38.8178329
61.1008
38.8103333
33.9315
15.3622
56.2023
36.5883331
38.7996674
46.4858333
63.073
35.747
33.4836667
-65.8111
-21.0853
36.409
36.8469
39.3936
36.847
60.4328
37.7416667
18.4178
36.5823333
56.9528
33.7491667
37.2765
62.1267
37.5993333
37.4065018
-18.5066
37.4641667
34.2021667
37.4638329
56.3627
33.5146667
36.5785
37.6026667
61.5563
36.4720001
43.1316
-20.4304
36.2804
33.4121667
64.1141
39.9068
62.2857
37.5265
38.8223343
61.4827
38.8181648
33.5063333
37.5091667
53.1545
38.8061676
46.8673333
60.5663
36.5561667
37.649
39.8327
37.6113333
33.4965
35.8458333
61.178
60.9841
46.9181667
37.5241667
37.5265
38.0425
53.1471
38.8436
36.5815
33.7135
46.14
19.4035
38.4445
33.4906667
46.16
-5.3473
33.9981667
33.4921667
33.411
34.2833333
37.5596657
33.656
33.996
39.714
37.741
63.3463
37.5588333
37.565834
18.422
18.0853
36.0743333
54.0368
18.262
62.1633
36.6091
43.759
58.1717
16.1547
34.0163333
33.9168333
39.5527
39.5506
43.5376667
17.9366
56.8636
61.5802
39.8185
61.5357
38.7322
33.4905
46.6211667
37.5315
33.469
37.6493333
38.8230019
35.7613333
38.7188
37.6511667
38.8144989
33.487
36.4703331
37.5995
61.7335
33.6946667
38.8370018
36.8544
38.836834
38.8371658
38.6683
-0.2312
19.2089996
38.8390007
33.685
37.6225
38.8185005
60.6977
33.9798333
38.8019981
36.2999
55.9679
57.6676
-31.5181
33.4926667
45.9393333
35.6783333
46.14
33.9763333
35.955
19.076
-6.4331
33.498
37.4938333
33.227
18.0783
19.4031667
33.1338333
60.1406
42.5203333
46.0153333
46.7798333
38.8031654
61.7344
37.9347
36.8557
39.2718
35.2891667
38.8306656
56.0622
46.15
33.4961667
44.7003333
18.115
61.1716
38.8156662
37.6143333
37.6183333
37.4968338
61.12
36.8523
-15.8045
36.598999
38.3505
36.012
63.0832
33.4875
33.4905
33.987
55.6829
33.4985
33.4828333
45.3796667
36.9938
33.874
33.6431667
19.1911659
56.098
61.6921
39.8225
18.0858
38.9103317
36.7926
36.5888329
61.7249
19.0276
33.2636667
38.8053322
36.8284
37.9908
36.0155
36.0181667
62.9644
39.9306
39.9314
39.9293
19.0641
64.7381
35.9935
39.8194
33.6621667
38.6872
37.2118
33.41
46.2016667
33.6568333
43.1508333
61.5271
33.148
37.4913333
37.4891667
61.7508
18.9946
39.8285
19.2108326
36.8496
60.9814
61.1799
33.399
37.1959
37.6256667
44.8015
19.1885
62.0331
33.7413333
61.172
61.2929
38.7906685
39.9228
43.1318
61.2905
56.4224
36.4500008
56.1421
64.8867
61.0423
38.8031654
46.8415
38.8095016
61.6231
33.4883333
33.5138333
56.1087
56.4549
66.1615
38.8025017
33.7396667
37.3779
61.7818
37.4741667
32.9333333
36.1615
37.7374992
-16.645
33.5296667
62.2437
-16.3907
38.7966652
35.994
38.8445015
33.8523333
61.7692
37.207
36.0078333
33.5093333
36.8661
55.8782
56.0559
38.8274994
36.4876671
36.5681667
37.4913333
38.6373329
52.1929
32.9203333
36.8669
46.6055
33.4878333
17.789
32.9281667
34.2335
37.0416667
33.5028333
38.7905006
38.3585
64.381
36.9259
19.3745
38.2054
38.7883339
37.5605
56.9051
55.8855
35.9961662
28.0626
38.8416672
63.2807
-4.5834
33.4863333
-8.4454
63.3824
19.7593333
39.8213333
37.1508
36.5828323
36.0928333
-1.6166
38.569
-56.9349
37.5423317
39.8056667
33.9283333
37.4500008
36.0121667
33.6741667
33.9433333
44.3391667
33.4363333
33.665
33.1358333
38.7896652
38.7896652
39.4151
37.5315
37.5613333
60.6803
36.1125
36.0
37.4638333
37.462
19.1396675
19.4141674
19.3895
46.7683333
61.8877
32.547
47.1899
38.5706667
38.8176651
37.1831665
36.4393333
37.4875
43.0945
36.083
18.327
-37.4597
62.248
33.6696667
37.6438333
33.5096667
47.5845
-1.7559
35.4643333
61.2651
39.7079
18.2475
36.7161
49.4463333
39.8253
34.1301667
38.8149986
34.0303333
38.822834
61.6483
64.7501
37.2823333
64.8106
33.6339
56.6162
33.7276667
40.516
35.0516667
33.822
44.2596667
33.4831667
18.0933
33.7873333
19.3465
45.9963333
56.4492
40.7456667
37.5788345
39.4116667
38.8383331
37.6106667
39.4121
33.4915
38.5065
63.0869
-10.7783
33.5113333
40.0853
38.8308334
46.6105
36.7533
32.9408333
63.7821
63.0173
64.5961
33.4943333
83.0126
56.1457
59.9613
57.8264
38.565
38.5735
37.497
37.2215
36.9518
7.4777
37.6218333
7.2307
37.0308333
37.6221667
57.6864
33.6676667
33.7851667
61.2318
36.0009995
45.6476667
39.799
59.7225
64.5379
37.8907
5.03
33.5036667
35.9918327
19.3476667
33.6726667
36.6648333
40.3892
33.787
11.8444
33.515
33.5066667
18.8385
46.1976667
18.5853
19.2893333
33.9295
58.2622
39.4284
19.2653332
32.6233333
33.7846667
61.3888
41.384
36.5465012
35.8151665
44.2606667
38.8343315
38.8356667
-6.9339
61.5596
36.8527
33.7511667
39.5403333
37.6618333
17.9593
46.1965
36.4981
37.5988333
35.8498333
36.4742
38.8409996
18.5001
37.4039
38.829834
37.1022
33.4858333
36.6053333
36.7959
56.2418
55.8754
36.463501
19.0398
60.0865
38.8305016
17.1958
37.332
39.9153333
56.5554
36.5608333
38.3704
39.7023
36.5631667
33.4935
36.8518
64.7269
33.7191667
33.7218333
37.6603333
60.2649
63.1041
38.8363342
63.7031
62.7937
46.9003333
36.5432
38.6874
63.2753
33.5563333
38.7896652
38.8358345
38.2442
65.2969
33.5038333
33.51
36.5453339
18.5481
38.4093
46.1983333
26.2946
33.5128333
61.4918
37.6101667
34.03
38.8321648
33.5015
38.8311653
36.8531
45.3735
38.6902
61.4305
36.8229
46.2041667
38.8256683
37.0945
36.2333333
36.2355
38.6901
-6.9796
67.8636
46.2021667
36.0248333
63.3829
18.5531
36.022
37.4681667
36.0295
46.14
59.8411
-28.3222
36.8543
-7.8628
44.8181667
46.2035

In [58]:
MAX_STEP = int(len(df)+1)

df['step'] = np.arange(1,MAX_STEP)

In [59]:
df

,type,id,properties.mag,properties.place,properties.time,properties.updated,properties.tz,properties.url,properties.detail,properties.felt,...,properties.gap,properties.magType,properties.type,properties.title,geometry.type,geometry.coordinates,Lat,Long,date_str,step
0,Feature,ci37868143,2.00,"4km W of Castaic, CA",1517966773840,1517966996303,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,174.0,ml,earthquake,"M 2.0 - 4km W of Castaic, CA",Point,"[-118.6671667, 34.4945, 26.49]",34.494500,-118.667167,1970-01-01 00:25:17.966773840,1
1,Feature,ci37868135,1.60,"2km E of San Marino, CA",1517966037750,1517966268248,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,141.0,ml,earthquake,"M 1.6 - 2km E of San Marino, CA",Point,"[-118.0873333, 34.12, 9.72]",34.120000,-118.087333,1970-01-01 00:25:17.966037750,2
2,Feature,ci37868127,0.54,"11km NE of Aguanga, CA",1517965273890,1517965499017,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,64.0,ml,earthquake,"M 0.5 - 11km NE of Aguanga, CA",Point,"[-116.7943333, 33.518, 5.04]",33.518000,-116.794333,1970-01-01 00:25:17.965273890,3
3,Feature,ak18384056,3.80,"300km SE of Kodiak, Alaska",1517964979027,1517966781617,-600,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,NaN,ml,earthquake,"M 3.8 - 300km SE of Kodiak, Alaska",Point,"[-149.145, 55.7729, 7.7]",55.772900,-149.145000,1970-01-01 00:25:17.964979027,4
4,Feature,nc72965406,0.66,"10km WNW of The Geysers, CA",1517964860110,1517965504730,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,80.0,md,earthquake,"M 0.7 - 10km WNW of The Geysers, CA",Point,"[-122.8560028, 38.8246651, 1.47]",38.824665,-122.856003,1970-01-01 00:25:17.964860110,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1702,Feature,us2000crl8,4.70,"232km ENE of Raoul Island, New Zealand",1517365017350,1517368678040,-720,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,142.0,mb,earthquake,"M 4.7 - 232km ENE of Raoul Island, New Zealand",Point,"[-175.7709, -28.3222, 10]",-28.322200,-175.770900,1970-01-01 00:25:17.365017350,1703
1703,Feature,us1000cdjq,2.00,"33km W of Raton, New Mexico",1517364466860,1517530950040,-420,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,89.0,ml,earthquake,"M 2.0 - 33km W of Raton, New Mexico",Point,"[-104.8072, 36.8543, 4.1]",36.854300,-104.807200,1970-01-01 00:25:17.364466860,1704
1704,Feature,us2000crkq,5.30,"50km NNW of Sangiang, Indonesia",1517364031800,1517423633040,480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,4.0,...,53.0,mb,earthquake,"M 5.3 - 50km NNW of Sangiang, Indonesia",Point,"[118.7906, -7.8628, 15.18]",-7.862800,118.790600,1970-01-01 00:25:17.364031800,1705
1705,Feature,mb80279649,1.35,"20km NNE of Lima, Montana",1517364015660,1517411000340,-420,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,115.0,ml,earthquake,"M 1.4 - 20km NNE of Lima, Montana",Point,"[-112.5183333, 44.8181667, -2.15]",44.818167,-112.518333,1970-01-01 00:25:17.364015660,1706
1706,Feature,uw61345682,0.31,"37km NNE of Amboy, Washington",1517363399650,1517942380200,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,108.0,ml,earthquake,"M 0.3 - 37km NNE of Amboy, Washington",Point,"[-122.197, 46.2035, 3.28]",46.203500,-122.197000,1970-01-01 00:25:17.363399650,1707

In [60]:
visible = df[df["step"] <= 1]

In [62]:
df[:100]

,type,id,properties.mag,properties.place,properties.time,properties.updated,properties.tz,properties.url,properties.detail,properties.felt,...,properties.gap,properties.magType,properties.type,properties.title,geometry.type,geometry.coordinates,Lat,Long,date_str,step
0,Feature,ci37868143,2.00,"4km W of Castaic, CA",1517966773840,1517966996303,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,174.00,ml,earthquake,"M 2.0 - 4km W of Castaic, CA",Point,"[-118.6671667, 34.4945, 26.49]",34.494500,-118.667167,1970-01-01 00:25:17.966773840,1
1,Feature,ci37868135,1.60,"2km E of San Marino, CA",1517966037750,1517966268248,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,141.00,ml,earthquake,"M 1.6 - 2km E of San Marino, CA",Point,"[-118.0873333, 34.12, 9.72]",34.120000,-118.087333,1970-01-01 00:25:17.966037750,2
2,Feature,ci37868127,0.54,"11km NE of Aguanga, CA",1517965273890,1517965499017,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,64.00,ml,earthquake,"M 0.5 - 11km NE of Aguanga, CA",Point,"[-116.7943333, 33.518, 5.04]",33.518000,-116.794333,1970-01-01 00:25:17.965273890,3
3,Feature,ak18384056,3.80,"300km SE of Kodiak, Alaska",1517964979027,1517966781617,-600,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,NaN,ml,earthquake,"M 3.8 - 300km SE of Kodiak, Alaska",Point,"[-149.145, 55.7729, 7.7]",55.772900,-149.145000,1970-01-01 00:25:17.964979027,4
4,Feature,nc72965406,0.66,"10km WNW of The Geysers, CA",1517964860110,1517965504730,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,80.00,md,earthquake,"M 0.7 - 10km WNW of The Geysers, CA",Point,"[-122.8560028, 38.8246651, 1.47]",38.824665,-122.856003,1970-01-01 00:25:17.964860110,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Feature,nc72965251,1.00,"5km NNE of Pinnacles, CA",1517921154960,1517925241715,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,101.00,md,earthquake,"M 1.0 - 5km NNE of Pinnacles, CA",Point,"[-121.1191635, 36.5750008, 11.21]",36.575001,-121.119163,1970-01-01 00:25:17.921154960,96
96,Feature,nc72965246,0.81,"9km NW of The Geysers, CA",1517920276240,1517923744668,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,114.00,md,earthquake,"M 0.8 - 9km NW of The Geysers, CA",Point,"[-122.831665, 38.8371658, 1.87]",38.837166,-122.831665,1970-01-01 00:25:17.920276240,97
97,Feature,nn00620854,0.70,"37km SE of Bridgeport, California",1517920088179,1517937653894,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,115.81,ml,earthquake,"M 0.7 - 37km SE of Bridgeport, California",Point,"[-118.8825, 38.0526, 9]",38.052600,-118.882500,1970-01-01 00:25:17.920088179,98
98,Feature,ci38100840,0.64,"13km ESE of Anza, CA",1517919336660,1517924800850,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,80.00,ml,earthquake,"M 0.6 - 13km ESE of Anza, CA",Point,"[-116.5515, 33.4958333, 10.32]",33.495833,-116.551500,1970-01-01 00:25:17.919336660,99
99,Feature,nc72965241,0.43,"3km SSW of Mammoth Lakes, CA",1517918929960,1517954822282,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,162.00,md,earthquake,"M 0.4 - 3km SSW of Mammoth Lakes, CA",Point,"[-118.9881667, 37.6145, 0.39]",37.614500,-118.988167,1970-01-01 00:25:17.918929960,100

In [61]:
visible

,type,id,properties.mag,properties.place,properties.time,properties.updated,properties.tz,properties.url,properties.detail,properties.felt,...,properties.gap,properties.magType,properties.type,properties.title,geometry.type,geometry.coordinates,Lat,Long,date_str,step
0,Feature,ci37868143,2.0,"4km W of Castaic, CA",1517966773840,1517966996303,-480,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/earthquakes/feed/v...,NaN,...,174.0,ml,earthquake,"M 2.0 - 4km W of Castaic, CA",Point,"[-118.6671667, 34.4945, 26.49]",34.4945,-118.667167,1970-01-01 00:25:17.966773840,1

In [ ]:
countries = alt.topo_feature(data.world_110m.url, "countries")

base = (
    alt.Chart(countries)
    .mark_geoshape(fill="lightgray", stroke="white")
    .project(type="naturalEarth1")
    .properties(width=900, height=480)
)
test = True
n = 36
start_ = 0
end_ = 50
track_ = 0
while track_< n and test==True:
    df_concat = pd.concat([df_concat, df[start_:end_]])
    points = (
    alt.Chart(df_concat)
    .mark_circle()
    .encode(
        longitude="Long:Q",
        latitude="Lat:Q",
        color=alt.Color(
            "magnitude:Q",
            scale=alt.Scale(scheme="inferno", domain=[df["magnitude"].min(), df["magnitude"].max()]),
            legend=alt.Legend(title="Magnitude")
        ),
        size=alt.Size(
            "magnitude:Q",
            scale=alt.Scale(range=[10, 400]),  # bigger points for larger magnitude
            legend=None
        ),
        tooltip=[
            "properties.place:N",
            "magnitude:Q",
            "date_str:T",
            "properties.type:N"
            ],
        )
    )
    chart = (base + points).properties(title="Adding Points Over Time (Play/Pause/Reset)")
    st.altair_chart(chart, use_container_width=True)
    track_ += 1
    start_ += 50
    end_ += 50